apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-web-app.fullname" . }}-backend
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  selector:
    {{- include "my-web-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend

